spring:
  application:
    name: mas-competition-backend
  datasource:
    url: jdbc:mariadb://mas-database-staging:3306/mascompetition
    driverClassName: org.mariadb.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update
server:
  port: 4500
agentStoragePath: '/app/agents/'
enginePath: '/app/mas-engine.jar'
next-round-cron-expression: "0 0/1 * * * *"