spring:
  application:
    name: mas-competition-backend
  datasource:
    # Within a bridged network localhost includes the other containers
    url: jdbc:mariadb://mas-database-production:3306/mascompetition
    driverClassName: org.mariadb.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update
server:
  port: 4000