spring:
  application:
    name: mas-competition-backend
  datasource:
    url: jdbc:mariadb://mas-database-production:3306/mascompetition
    driverClassName: org.mariadb.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: create-drop
server:
  port: 4000
agentStoragePath: '/app/agents'
enginePath: '/app/mas-engine.jar'
next-round-cron-expression: "0 0/15 * * * *"