spring:
  application:
    name: mas-competition-backend
  datasource:
    url: jdbc:mariadb://mas-database-staging:3306/mascompetition
    driverClassName: org.mariadb.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: create-drop
server:
  port: 4500
agentStorageLocation: '/home/jfa93/agents/test/'