spring:
  application:
    name: mas-competition-backend
  datasource:
    url: jdbc:mariadb://localhost:2300/mascompetition
    driverClassName: org.mariadb.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update
server:
  port: 4300
agentStoragePath: './agents/'
enginePath: './mas-engine-1.0.jar'
next-round-cron-expression: '0/20 * * * * *'