spring:
  application:
    name: mas-competition-backend
  datasource:
    # Within a bridged network localhost includes the other containers
    # On the VM this will be accessible through port 2500
    url: jdbc:mariadb://host.docker.internal:2500/mascompetition
    driverClassName: org.mariadb.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update
server:
  port: 4500