services:
  mas-database-production:
    container_name: mas-database-production
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mascompetition
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "2000:3306"
    volumes:
      - /home/jfa93/volumes/mas-prod-database:/var/lib/mysql

  adminer-production:
    container_name: mas-adminer-production
    image: adminer
    restart: always
    ports:
      - "8000:8080"

  mas-backend-production:
    image: mas-competition-backend-production
    restart: always
    depends_on:
      - mas-database-production
    ports:
      - "4000:4000"
    volumes:
      - /home/jfa93/volumes/mas-prod-agents:/app/agents
