services:
  mas-database-production:
    container_name: mas-database-production
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mascompetition
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "2000:3306"
    volumes:
      - mas-database-data-production:/var/lib/mysql

  adminer-production:
    container_name: mas-adminer-production
    image: adminer
    restart: always
    ports:
      - "8000:8080"

  mas-backend-production:
    image: mas-competition-backend-production
    restart: always
    depends_on:
      - mas-database-production
    ports:
      - "4000:4000"
    volumes:
      - mas-agent-volume-production:/app/agents

volumes:
  mas-agent-volume-production:
  mas-database-data-production: