services:
  mas-database-production:
    container_name: mas-database-production
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mascompetition
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    env_file:
      - .env
    ports:
      - "2000:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql

  mas-competition-backend-production:
    image: mas-competition-backend-production
    restart: always
    depends_on:
      - mas-database-production
    ports:
      - "4000:4000"

volumes:
  mariadb-volume:
