services:
  mas-database-staging:
    container_name: mas-database-staging
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mascompetition
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "2500:3306"
    volumes:
      - /home/jfa93/volumes/mas-staging-database:/var/lib/mysql

  adminer-staging:
    container_name: mas-adminer-staging
    image: adminer
    restart: always
    ports:
      - "8500:8080"

  mas-backend-staging:
    image: mas-competition-backend-staging
    restart: always
    depends_on:
      - mas-database-staging
    ports:
      - "4500:4500"
    volumes:
      - /home/jfa93/volumes/mas-staging-agents:/app/agents
