services:
  mas-database-staging:
    container_name: mas-database-staging
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mascompetition
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      port:
    ports:
      - "2500:3306"
    network_mode: host

  adminer-staging:
    container_name: mas-adminer-staging
    image: adminer
    restart: always
    ports:
      - "8500:8080"
    network_mode: host

  mas-competition-backend-staging:
    image: mas-competition-backend-staging
    restart: always
    depends_on:
      - mas-database-staging
    ports:
      - "4500:4500"
    network_mode: host
