name: mas-competition-backend-deployment

on:
  push:
    branches: [master]

env:
  PRODUCTION_DB_USER: ${{ secrets.PRODUCTION_DB_USER }}
  PRODUCTION_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checking secrets
        run: echo ${PRODUCTION_DB_USER}

      - name: Clear workspace
        run: echo ${{ secrets.USERPWD }} | sudo rm -rf $GITHUB_WORKSPACE/*

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache repository
        uses: actions/cache@v2
        with:
          path: ~/.cache/repo
          key: ${{ runner.os }}-repo-${{ hashFiles('.git/index') }}

      - name: Permissions
        run: chmod u+x ./gradlew

      - name: Start Test DB
        run: echo ${{ secrets.USERPWD }} | sudo docker compose -f ./docker/dev/docker-compose.yaml up -d

      - name: Run Backend Tests
        run: ./gradlew test

      - name: Stopping Test DB
        run: echo ${{ secrets.USERPWD }} | sudo docker compose -f ./docker/dev/docker-compose.yaml down

  build-staging:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Restore cached repository
        uses: actions/cache@v2
        with:
          path: ~/.cache/repo
          key: ${{ runner.os }}-repo-${{ hashFiles('.git/index') }}

      - name: Permissions
        run: chmod u+x ./docker/staging/buildStaging.sh && chmod u+x ./gradlew

      - name: Build Docker Image
        run: echo ${{ secrets.USERPWD }} | sudo ./docker/staging/buildStaging.sh

  deploy-staging:
    runs-on: self-hosted
    needs: build-staging
    steps:
      - name: Restore cached repository
        uses: actions/cache@v2
        with:
          path: ~/.cache/repo
          key: ${{ runner.os }}-repo-${{ hashFiles('.git/index') }}

      - name: Restart Server
        run: |
          cd ./docker/staging
          echo ${{ secrets.USERPWD }} | sudo docker compose down
          echo ${{ secrets.USERPWD }} | sudo docker compose up  -d

  build-production:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Restore cached repository
        uses: actions/cache@v2
        with:
          path: ~/.cache/repo
          key: ${{ runner.os }}-repo-${{ hashFiles('.git/index') }}

      - name: Permissions
        run: chmod u+x ./docker/production/buildProduction.sh && chmod u+x ./gradlew

      - name: Build Docker Image
        run: echo ${{ secrets.USERPWD }} | sudo ./docker/production/buildProduction.sh

  deploy-production:
    runs-on: self-hosted
    needs: build-production
    steps:
      - name: Restore cached repository
        uses: actions/cache@v2
        with:
          path: ~/.cache/repo
          key: ${{ runner.os }}-repo-${{ hashFiles('.git/index') }}

      - name: Restart Server
        run: |
          cd ./docker/production
          echo ${{ secrets.USERPWD }} | sudo docker compose down
          echo ${{ secrets.USERPWD }} | sudo docker compose up  -d
