name: mas-competition-backend-deployment

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Permissions
        run: chmod u+x ./gradlew

      - name: Start Test DB
        run: echo ${{ secrets.USERPWD }} | sudo docker compose -f ./docker/dev/docker-compose.yaml up -d

      - name: Run Backend Tests
        run: ./gradlew test

      - name: Stopping Test DB
        run: echo ${{ secrets.USERPWD }} | sudo docker compose -f ./docker/dev/docker-compose.yaml down

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Permissions
        run: chmod u+x ./docker/stagingContainer.sh

      - name: Build Docker Image
        run: ./docker/stagingContainer.sh

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Restart Server
        run: |
          cd ./docker/staging
          echo ${{ secrets.USERPWD }} | sudo docker compose down
          echo ${{ secrets.USERPWD }} | sudo docker compose up  -d
